In [1]:
import numpy as np
import pandas as pd

#Question 1

In [2]:
np.__version__

'1.21.6'

In [3]:
df = pd.read_csv("data.csv")
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

# Question 2

In [32]:
df.shape[0]

11914

# Question 3

In [34]:
grouped = df.groupby("Make").count()
grouped.sort_values("Model", ascending=False).head(3)

Model  Year  Engine Fuel Type  Engine HP  Engine Cylinders  \
Make                                                                     
Chevrolet    1123  1123              1123       1117              1121   
Ford          881   881               881        868               881   
Volkswagen    809   809               809        809               805   

            Transmission Type  Driven_Wheels  Number of Doors  \
Make                                                            
Chevrolet                1123           1123             1123   
Ford                      881            881              881   
Volkswagen                809            809              809   

            Market Category  Vehicle Size  Vehicle Style  highway MPG  \
Make                                                                    
Chevrolet               622          1123           1123         1123   
Ford                    499           881            881          881   
Volkswagen              585           809            809          809   

            city mpg  Popularity  MSRP  
Make                                    
Chevrolet       1123        1123  1123  
Ford             881         881   881  
Volkswagen       809         809   809

# Question 4

In [35]:
audi_df = df[df["Make"] == "Audi"]
audi_df["Model"].nunique()

34

# Question 5

In [40]:
result = df.isnull().sum()
nulls = [x for x in result if x != 0]
len(nulls)

5

# Question 6

In [17]:
median = df["Engine Cylinders"].median()
print(f'Original Median is {median}')
mode = df["Engine Cylinders"].mode()
df["Engine Cylinders"] = df["Engine Cylinders"].fillna(mode)
median2 = df["Engine Cylinders"].median()
print(f'After filling NaNs, the new median is {median2}')


Original Median is 6.0
After filling NaNs, the new median is 6.0


# Question 7

In [22]:
lotus_df = df[df["Make"] == "Lotus"]
lotus_df = lotus_df[["Engine HP", "Engine Cylinders"]]
lotus_df.drop_duplicates(inplace=True)
X = lotus_df.to_numpy()
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [29]:
X_transpose = X.T
XTX = X_transpose.dot(X)
XTX_inv = np.linalg.inv(XTX)
XTX_inv


array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [31]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
#w = (XTX_inv * X_transpose) * y
w = XTX_inv.dot(X_transpose).dot(y)
w

array([  4.59494481, -63.56432501])